project:
  type: website
  output-dir : docs

website:
  favicon: '/images/logo.png'
  #title: "<img src='/images/logo.png' width='10%' height='10%'/>"
  reader-mode: true
  navbar:
    logo: /images/logo.png
    tools:
      - icon: github
        href: https://github.com/hizocar
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:AboutMe
      - sidebar:Courses

  sidebar:
   - id: AboutMe
     style: "docked"
     search: true
     contents: 
       - section: "AboutMe"
         contents:
          - personal/perfil.qmd
          - personal/academica.qmd
          - personal/laboral.qmd
   - id: Courses
     style: "docked"
     search: true
     contents:
      - section: "Data Science for Math Engineers (USACH)"
        contents:
          - data_science_ingemat/programa.qmd
          - data_science_ingemat/presentacion.qmd
          - section: "Modulo 2: Series de Tiempo"
            contents:
              - data_science_ingemat/modulo2/introduccion.qmd
              - data_science_ingemat/modulo2/estacionaria.qmd
              - data_science_ingemat/modulo2/prophet.qmd
              - data_science_ingemat/modulo2/ARIMA_SARIMA_Tutorial.ipynb
              - data_science_ingemat/modulo2/proyecto2.qmd
              - data_science_ingemat/modulo2/complemento.qmd
format:
  html:
    theme: 
          light: minty
          dark: [minty, theme-dark.scss]
    css: styles.css
    toc: true





